# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Aline Botelho"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "Sobre"
weight = 2


[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "61 99511-9932"
email = "alinnyfb@gmail.com"
# meta description
author = "Aline Botelho"
description = "Aline Botelho - UI/UX Designer"
# google analitycs
google_analitycs_id = "" # Your ID
# copyright
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://www.linkedin.com/in/aline-botelho"
icon = "ti-linkedin"